version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: order
      MONGO_INITDB_ROOT_USERNAME: order
      MONGO_INITDB_ROOT_PASSWORD: item
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://order:item@mongodb:27017/
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=order
      - ME_CONFIG_MONGODB_ADMINPASSWORD=item
      - ME_CONFIG_BASICAUTH_USERNAME=order
      - ME_CONFIG_BASICAUTH_PASSWORD=item
    links:
      - mongodb
    ports:
      - 8081:8081
